import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Raleway } from 'next/font/google';



import './globals.css';
import { Header } from './(landing)/_components/header';
import { Footer } from './(landing)/_components/footer';
import classNames from 'classnames';

const montserrat = Montserrat({ subsets: ['latin'] });
const raleway = Raleway({ subsets: ['latin'] });

//NEXT ART ?

export const metadata: Metadata = {
  title: 'Аристомед',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          montserrat.className,
          //  raleway.className
        )}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
