import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Raleway } from 'next/font/google';

import '../assets/styles/globals.css';
import { Header } from '../components/layout/header/header';
import { Footer } from '../components/layout/footer';
import classNames from 'classnames';
import { Provider } from 'react-redux';
import { store } from '../store/store';
import Providers from '@/utils/providers';

const montserrat = Montserrat({ subsets: ['latin'] });
const raleway = Raleway({ subsets: ['latin'] });

//NEXT ART ?

export const metadata: Metadata = {
  title: 'Аристомед',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          montserrat.className,
          //  raleway.className
        )}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
